version: '3.1'

services:
    # https://hub.docker.com/_/postgres
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: kopf3
            POSTGRES_PASSWORD: mshack
